#ifndef COMM_PROTOCOL_H
#define COMM_PROTOCOL_H

#define PROTOCOL__FRAME_IMAGE 0x10
#define PROTOCOL__REQUEST_COLORS 0x20
#define PROTOCOL__COLORS_INFO 0x21
#define PROTOCOL__COLOR_INFO 0x22
#define PROTOCOL__LOAD_COLORS 0x25
#define PROTOCOL__SAVE_COLORS 0x26

#endif
