// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

public interface ColorsInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:c22dlink.ColorsInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  java.util.List<c22dlink.ColorInfo> 
      getColorsList();
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  c22dlink.ColorInfo getColors(int index);
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  int getColorsCount();
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  java.util.List<? extends c22dlink.ColorInfoOrBuilder> 
      getColorsOrBuilderList();
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  c22dlink.ColorInfoOrBuilder getColorsOrBuilder(
      int index);
}
