// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

/**
 * Protobuf type {@code c22dlink.ColorInfo}
 */
public final class ColorInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:c22dlink.ColorInfo)
    ColorInfoOrBuilder {
  // Use ColorInfo.newBuilder() to construct.
  private ColorInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ColorInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ColorInfo defaultInstance;
  public static ColorInfo getDefaultInstance() {
    return defaultInstance;
  }

  public ColorInfo getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ColorInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            c22dlink.RGB.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = rgb_.toBuilder();
            }
            rgb_ = input.readMessage(c22dlink.RGB.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rgb_);
              rgb_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            name_ = bs;
            break;
          }
          case 33: {
            bitField0_ |= 0x00000008;
            merge_ = input.readDouble();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            expected_ = input.readInt32();
            break;
          }
          case 50: {
            c22dlink.YUV.Builder subBuilder = null;
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
              subBuilder = yuvLow_.toBuilder();
            }
            yuvLow_ = input.readMessage(c22dlink.YUV.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(yuvLow_);
              yuvLow_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000020;
            break;
          }
          case 58: {
            c22dlink.YUV.Builder subBuilder = null;
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
              subBuilder = yuvHigh_.toBuilder();
            }
            yuvHigh_ = input.readMessage(c22dlink.YUV.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(yuvHigh_);
              yuvHigh_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000040;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return c22dlink.Colors.internal_static_c22dlink_ColorInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return c22dlink.Colors.internal_static_c22dlink_ColorInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            c22dlink.ColorInfo.class, c22dlink.ColorInfo.Builder.class);
  }

  public static com.google.protobuf.Parser<ColorInfo> PARSER =
      new com.google.protobuf.AbstractParser<ColorInfo>() {
    public ColorInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ColorInfo(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ColorInfo> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>required int32 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int RGB_FIELD_NUMBER = 2;
  private c22dlink.RGB rgb_;
  /**
   * <code>optional .c22dlink.RGB rgb = 2;</code>
   */
  public boolean hasRgb() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .c22dlink.RGB rgb = 2;</code>
   */
  public c22dlink.RGB getRgb() {
    return rgb_;
  }
  /**
   * <code>optional .c22dlink.RGB rgb = 2;</code>
   */
  public c22dlink.RGBOrBuilder getRgbOrBuilder() {
    return rgb_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private java.lang.Object name_;
  /**
   * <code>optional string name = 3;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MERGE_FIELD_NUMBER = 4;
  private double merge_;
  /**
   * <code>required double merge = 4;</code>
   */
  public boolean hasMerge() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required double merge = 4;</code>
   */
  public double getMerge() {
    return merge_;
  }

  public static final int EXPECTED_FIELD_NUMBER = 5;
  private int expected_;
  /**
   * <code>required int32 expected = 5;</code>
   */
  public boolean hasExpected() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required int32 expected = 5;</code>
   */
  public int getExpected() {
    return expected_;
  }

  public static final int YUVLOW_FIELD_NUMBER = 6;
  private c22dlink.YUV yuvLow_;
  /**
   * <code>required .c22dlink.YUV yuvLow = 6;</code>
   */
  public boolean hasYuvLow() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>required .c22dlink.YUV yuvLow = 6;</code>
   */
  public c22dlink.YUV getYuvLow() {
    return yuvLow_;
  }
  /**
   * <code>required .c22dlink.YUV yuvLow = 6;</code>
   */
  public c22dlink.YUVOrBuilder getYuvLowOrBuilder() {
    return yuvLow_;
  }

  public static final int YUVHIGH_FIELD_NUMBER = 7;
  private c22dlink.YUV yuvHigh_;
  /**
   * <code>required .c22dlink.YUV yuvHigh = 7;</code>
   */
  public boolean hasYuvHigh() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>required .c22dlink.YUV yuvHigh = 7;</code>
   */
  public c22dlink.YUV getYuvHigh() {
    return yuvHigh_;
  }
  /**
   * <code>required .c22dlink.YUV yuvHigh = 7;</code>
   */
  public c22dlink.YUVOrBuilder getYuvHighOrBuilder() {
    return yuvHigh_;
  }

  private void initFields() {
    id_ = 0;
    rgb_ = c22dlink.RGB.getDefaultInstance();
    name_ = "";
    merge_ = 0D;
    expected_ = 0;
    yuvLow_ = c22dlink.YUV.getDefaultInstance();
    yuvHigh_ = c22dlink.YUV.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMerge()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasExpected()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasYuvLow()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasYuvHigh()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasRgb()) {
      if (!getRgb().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!getYuvLow().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getYuvHigh().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, rgb_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getNameBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeDouble(4, merge_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, expected_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeMessage(6, yuvLow_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeMessage(7, yuvHigh_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rgb_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getNameBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, merge_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, expected_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, yuvLow_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, yuvHigh_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static c22dlink.ColorInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.ColorInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.ColorInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.ColorInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.ColorInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.ColorInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static c22dlink.ColorInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static c22dlink.ColorInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static c22dlink.ColorInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.ColorInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(c22dlink.ColorInfo prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code c22dlink.ColorInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:c22dlink.ColorInfo)
      c22dlink.ColorInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return c22dlink.Colors.internal_static_c22dlink_ColorInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return c22dlink.Colors.internal_static_c22dlink_ColorInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              c22dlink.ColorInfo.class, c22dlink.ColorInfo.Builder.class);
    }

    // Construct using c22dlink.ColorInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRgbFieldBuilder();
        getYuvLowFieldBuilder();
        getYuvHighFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (rgbBuilder_ == null) {
        rgb_ = c22dlink.RGB.getDefaultInstance();
      } else {
        rgbBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      merge_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000008);
      expected_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (yuvLowBuilder_ == null) {
        yuvLow_ = c22dlink.YUV.getDefaultInstance();
      } else {
        yuvLowBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (yuvHighBuilder_ == null) {
        yuvHigh_ = c22dlink.YUV.getDefaultInstance();
      } else {
        yuvHighBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return c22dlink.Colors.internal_static_c22dlink_ColorInfo_descriptor;
    }

    public c22dlink.ColorInfo getDefaultInstanceForType() {
      return c22dlink.ColorInfo.getDefaultInstance();
    }

    public c22dlink.ColorInfo build() {
      c22dlink.ColorInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public c22dlink.ColorInfo buildPartial() {
      c22dlink.ColorInfo result = new c22dlink.ColorInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (rgbBuilder_ == null) {
        result.rgb_ = rgb_;
      } else {
        result.rgb_ = rgbBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.merge_ = merge_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.expected_ = expected_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      if (yuvLowBuilder_ == null) {
        result.yuvLow_ = yuvLow_;
      } else {
        result.yuvLow_ = yuvLowBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      if (yuvHighBuilder_ == null) {
        result.yuvHigh_ = yuvHigh_;
      } else {
        result.yuvHigh_ = yuvHighBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof c22dlink.ColorInfo) {
        return mergeFrom((c22dlink.ColorInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(c22dlink.ColorInfo other) {
      if (other == c22dlink.ColorInfo.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasRgb()) {
        mergeRgb(other.getRgb());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000004;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasMerge()) {
        setMerge(other.getMerge());
      }
      if (other.hasExpected()) {
        setExpected(other.getExpected());
      }
      if (other.hasYuvLow()) {
        mergeYuvLow(other.getYuvLow());
      }
      if (other.hasYuvHigh()) {
        mergeYuvHigh(other.getYuvHigh());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasId()) {
        
        return false;
      }
      if (!hasMerge()) {
        
        return false;
      }
      if (!hasExpected()) {
        
        return false;
      }
      if (!hasYuvLow()) {
        
        return false;
      }
      if (!hasYuvHigh()) {
        
        return false;
      }
      if (hasRgb()) {
        if (!getRgb().isInitialized()) {
          
          return false;
        }
      }
      if (!getYuvLow().isInitialized()) {
        
        return false;
      }
      if (!getYuvHigh().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      c22dlink.ColorInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (c22dlink.ColorInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private c22dlink.RGB rgb_ = c22dlink.RGB.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        c22dlink.RGB, c22dlink.RGB.Builder, c22dlink.RGBOrBuilder> rgbBuilder_;
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public boolean hasRgb() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public c22dlink.RGB getRgb() {
      if (rgbBuilder_ == null) {
        return rgb_;
      } else {
        return rgbBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public Builder setRgb(c22dlink.RGB value) {
      if (rgbBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rgb_ = value;
        onChanged();
      } else {
        rgbBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public Builder setRgb(
        c22dlink.RGB.Builder builderForValue) {
      if (rgbBuilder_ == null) {
        rgb_ = builderForValue.build();
        onChanged();
      } else {
        rgbBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public Builder mergeRgb(c22dlink.RGB value) {
      if (rgbBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            rgb_ != c22dlink.RGB.getDefaultInstance()) {
          rgb_ =
            c22dlink.RGB.newBuilder(rgb_).mergeFrom(value).buildPartial();
        } else {
          rgb_ = value;
        }
        onChanged();
      } else {
        rgbBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public Builder clearRgb() {
      if (rgbBuilder_ == null) {
        rgb_ = c22dlink.RGB.getDefaultInstance();
        onChanged();
      } else {
        rgbBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public c22dlink.RGB.Builder getRgbBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getRgbFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    public c22dlink.RGBOrBuilder getRgbOrBuilder() {
      if (rgbBuilder_ != null) {
        return rgbBuilder_.getMessageOrBuilder();
      } else {
        return rgb_;
      }
    }
    /**
     * <code>optional .c22dlink.RGB rgb = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        c22dlink.RGB, c22dlink.RGB.Builder, c22dlink.RGBOrBuilder> 
        getRgbFieldBuilder() {
      if (rgbBuilder_ == null) {
        rgbBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            c22dlink.RGB, c22dlink.RGB.Builder, c22dlink.RGBOrBuilder>(
                getRgb(),
                getParentForChildren(),
                isClean());
        rgb_ = null;
      }
      return rgbBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      name_ = value;
      onChanged();
      return this;
    }

    private double merge_ ;
    /**
     * <code>required double merge = 4;</code>
     */
    public boolean hasMerge() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double merge = 4;</code>
     */
    public double getMerge() {
      return merge_;
    }
    /**
     * <code>required double merge = 4;</code>
     */
    public Builder setMerge(double value) {
      bitField0_ |= 0x00000008;
      merge_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double merge = 4;</code>
     */
    public Builder clearMerge() {
      bitField0_ = (bitField0_ & ~0x00000008);
      merge_ = 0D;
      onChanged();
      return this;
    }

    private int expected_ ;
    /**
     * <code>required int32 expected = 5;</code>
     */
    public boolean hasExpected() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 expected = 5;</code>
     */
    public int getExpected() {
      return expected_;
    }
    /**
     * <code>required int32 expected = 5;</code>
     */
    public Builder setExpected(int value) {
      bitField0_ |= 0x00000010;
      expected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 expected = 5;</code>
     */
    public Builder clearExpected() {
      bitField0_ = (bitField0_ & ~0x00000010);
      expected_ = 0;
      onChanged();
      return this;
    }

    private c22dlink.YUV yuvLow_ = c22dlink.YUV.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        c22dlink.YUV, c22dlink.YUV.Builder, c22dlink.YUVOrBuilder> yuvLowBuilder_;
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public boolean hasYuvLow() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public c22dlink.YUV getYuvLow() {
      if (yuvLowBuilder_ == null) {
        return yuvLow_;
      } else {
        return yuvLowBuilder_.getMessage();
      }
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public Builder setYuvLow(c22dlink.YUV value) {
      if (yuvLowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        yuvLow_ = value;
        onChanged();
      } else {
        yuvLowBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public Builder setYuvLow(
        c22dlink.YUV.Builder builderForValue) {
      if (yuvLowBuilder_ == null) {
        yuvLow_ = builderForValue.build();
        onChanged();
      } else {
        yuvLowBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public Builder mergeYuvLow(c22dlink.YUV value) {
      if (yuvLowBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            yuvLow_ != c22dlink.YUV.getDefaultInstance()) {
          yuvLow_ =
            c22dlink.YUV.newBuilder(yuvLow_).mergeFrom(value).buildPartial();
        } else {
          yuvLow_ = value;
        }
        onChanged();
      } else {
        yuvLowBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public Builder clearYuvLow() {
      if (yuvLowBuilder_ == null) {
        yuvLow_ = c22dlink.YUV.getDefaultInstance();
        onChanged();
      } else {
        yuvLowBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public c22dlink.YUV.Builder getYuvLowBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getYuvLowFieldBuilder().getBuilder();
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    public c22dlink.YUVOrBuilder getYuvLowOrBuilder() {
      if (yuvLowBuilder_ != null) {
        return yuvLowBuilder_.getMessageOrBuilder();
      } else {
        return yuvLow_;
      }
    }
    /**
     * <code>required .c22dlink.YUV yuvLow = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        c22dlink.YUV, c22dlink.YUV.Builder, c22dlink.YUVOrBuilder> 
        getYuvLowFieldBuilder() {
      if (yuvLowBuilder_ == null) {
        yuvLowBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            c22dlink.YUV, c22dlink.YUV.Builder, c22dlink.YUVOrBuilder>(
                getYuvLow(),
                getParentForChildren(),
                isClean());
        yuvLow_ = null;
      }
      return yuvLowBuilder_;
    }

    private c22dlink.YUV yuvHigh_ = c22dlink.YUV.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        c22dlink.YUV, c22dlink.YUV.Builder, c22dlink.YUVOrBuilder> yuvHighBuilder_;
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public boolean hasYuvHigh() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public c22dlink.YUV getYuvHigh() {
      if (yuvHighBuilder_ == null) {
        return yuvHigh_;
      } else {
        return yuvHighBuilder_.getMessage();
      }
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public Builder setYuvHigh(c22dlink.YUV value) {
      if (yuvHighBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        yuvHigh_ = value;
        onChanged();
      } else {
        yuvHighBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public Builder setYuvHigh(
        c22dlink.YUV.Builder builderForValue) {
      if (yuvHighBuilder_ == null) {
        yuvHigh_ = builderForValue.build();
        onChanged();
      } else {
        yuvHighBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public Builder mergeYuvHigh(c22dlink.YUV value) {
      if (yuvHighBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040) &&
            yuvHigh_ != c22dlink.YUV.getDefaultInstance()) {
          yuvHigh_ =
            c22dlink.YUV.newBuilder(yuvHigh_).mergeFrom(value).buildPartial();
        } else {
          yuvHigh_ = value;
        }
        onChanged();
      } else {
        yuvHighBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public Builder clearYuvHigh() {
      if (yuvHighBuilder_ == null) {
        yuvHigh_ = c22dlink.YUV.getDefaultInstance();
        onChanged();
      } else {
        yuvHighBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public c22dlink.YUV.Builder getYuvHighBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getYuvHighFieldBuilder().getBuilder();
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    public c22dlink.YUVOrBuilder getYuvHighOrBuilder() {
      if (yuvHighBuilder_ != null) {
        return yuvHighBuilder_.getMessageOrBuilder();
      } else {
        return yuvHigh_;
      }
    }
    /**
     * <code>required .c22dlink.YUV yuvHigh = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        c22dlink.YUV, c22dlink.YUV.Builder, c22dlink.YUVOrBuilder> 
        getYuvHighFieldBuilder() {
      if (yuvHighBuilder_ == null) {
        yuvHighBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            c22dlink.YUV, c22dlink.YUV.Builder, c22dlink.YUVOrBuilder>(
                getYuvHigh(),
                getParentForChildren(),
                isClean());
        yuvHigh_ = null;
      }
      return yuvHighBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:c22dlink.ColorInfo)
  }

  static {
    defaultInstance = new ColorInfo(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:c22dlink.ColorInfo)
}

