// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

/**
 * Protobuf type {@code c22dlink.ColorsInfo}
 */
public final class ColorsInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:c22dlink.ColorsInfo)
    ColorsInfoOrBuilder {
  // Use ColorsInfo.newBuilder() to construct.
  private ColorsInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ColorsInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ColorsInfo defaultInstance;
  public static ColorsInfo getDefaultInstance() {
    return defaultInstance;
  }

  public ColorsInfo getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ColorsInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              colors_ = new java.util.ArrayList<c22dlink.ColorInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            colors_.add(input.readMessage(c22dlink.ColorInfo.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        colors_ = java.util.Collections.unmodifiableList(colors_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return c22dlink.Colors.internal_static_c22dlink_ColorsInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return c22dlink.Colors.internal_static_c22dlink_ColorsInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            c22dlink.ColorsInfo.class, c22dlink.ColorsInfo.Builder.class);
  }

  public static com.google.protobuf.Parser<ColorsInfo> PARSER =
      new com.google.protobuf.AbstractParser<ColorsInfo>() {
    public ColorsInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ColorsInfo(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ColorsInfo> getParserForType() {
    return PARSER;
  }

  public static final int COLORS_FIELD_NUMBER = 1;
  private java.util.List<c22dlink.ColorInfo> colors_;
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  public java.util.List<c22dlink.ColorInfo> getColorsList() {
    return colors_;
  }
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  public java.util.List<? extends c22dlink.ColorInfoOrBuilder> 
      getColorsOrBuilderList() {
    return colors_;
  }
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  public int getColorsCount() {
    return colors_.size();
  }
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  public c22dlink.ColorInfo getColors(int index) {
    return colors_.get(index);
  }
  /**
   * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
   */
  public c22dlink.ColorInfoOrBuilder getColorsOrBuilder(
      int index) {
    return colors_.get(index);
  }

  private void initFields() {
    colors_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getColorsCount(); i++) {
      if (!getColors(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < colors_.size(); i++) {
      output.writeMessage(1, colors_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < colors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, colors_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static c22dlink.ColorsInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.ColorsInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.ColorsInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.ColorsInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.ColorsInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.ColorsInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static c22dlink.ColorsInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static c22dlink.ColorsInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static c22dlink.ColorsInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.ColorsInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(c22dlink.ColorsInfo prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code c22dlink.ColorsInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:c22dlink.ColorsInfo)
      c22dlink.ColorsInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return c22dlink.Colors.internal_static_c22dlink_ColorsInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return c22dlink.Colors.internal_static_c22dlink_ColorsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              c22dlink.ColorsInfo.class, c22dlink.ColorsInfo.Builder.class);
    }

    // Construct using c22dlink.ColorsInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getColorsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (colorsBuilder_ == null) {
        colors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        colorsBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return c22dlink.Colors.internal_static_c22dlink_ColorsInfo_descriptor;
    }

    public c22dlink.ColorsInfo getDefaultInstanceForType() {
      return c22dlink.ColorsInfo.getDefaultInstance();
    }

    public c22dlink.ColorsInfo build() {
      c22dlink.ColorsInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public c22dlink.ColorsInfo buildPartial() {
      c22dlink.ColorsInfo result = new c22dlink.ColorsInfo(this);
      int from_bitField0_ = bitField0_;
      if (colorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          colors_ = java.util.Collections.unmodifiableList(colors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.colors_ = colors_;
      } else {
        result.colors_ = colorsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof c22dlink.ColorsInfo) {
        return mergeFrom((c22dlink.ColorsInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(c22dlink.ColorsInfo other) {
      if (other == c22dlink.ColorsInfo.getDefaultInstance()) return this;
      if (colorsBuilder_ == null) {
        if (!other.colors_.isEmpty()) {
          if (colors_.isEmpty()) {
            colors_ = other.colors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColorsIsMutable();
            colors_.addAll(other.colors_);
          }
          onChanged();
        }
      } else {
        if (!other.colors_.isEmpty()) {
          if (colorsBuilder_.isEmpty()) {
            colorsBuilder_.dispose();
            colorsBuilder_ = null;
            colors_ = other.colors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            colorsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getColorsFieldBuilder() : null;
          } else {
            colorsBuilder_.addAllMessages(other.colors_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getColorsCount(); i++) {
        if (!getColors(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      c22dlink.ColorsInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (c22dlink.ColorsInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<c22dlink.ColorInfo> colors_ =
      java.util.Collections.emptyList();
    private void ensureColorsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        colors_ = new java.util.ArrayList<c22dlink.ColorInfo>(colors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        c22dlink.ColorInfo, c22dlink.ColorInfo.Builder, c22dlink.ColorInfoOrBuilder> colorsBuilder_;

    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public java.util.List<c22dlink.ColorInfo> getColorsList() {
      if (colorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(colors_);
      } else {
        return colorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public int getColorsCount() {
      if (colorsBuilder_ == null) {
        return colors_.size();
      } else {
        return colorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public c22dlink.ColorInfo getColors(int index) {
      if (colorsBuilder_ == null) {
        return colors_.get(index);
      } else {
        return colorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder setColors(
        int index, c22dlink.ColorInfo value) {
      if (colorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColorsIsMutable();
        colors_.set(index, value);
        onChanged();
      } else {
        colorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder setColors(
        int index, c22dlink.ColorInfo.Builder builderForValue) {
      if (colorsBuilder_ == null) {
        ensureColorsIsMutable();
        colors_.set(index, builderForValue.build());
        onChanged();
      } else {
        colorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder addColors(c22dlink.ColorInfo value) {
      if (colorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColorsIsMutable();
        colors_.add(value);
        onChanged();
      } else {
        colorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder addColors(
        int index, c22dlink.ColorInfo value) {
      if (colorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColorsIsMutable();
        colors_.add(index, value);
        onChanged();
      } else {
        colorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder addColors(
        c22dlink.ColorInfo.Builder builderForValue) {
      if (colorsBuilder_ == null) {
        ensureColorsIsMutable();
        colors_.add(builderForValue.build());
        onChanged();
      } else {
        colorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder addColors(
        int index, c22dlink.ColorInfo.Builder builderForValue) {
      if (colorsBuilder_ == null) {
        ensureColorsIsMutable();
        colors_.add(index, builderForValue.build());
        onChanged();
      } else {
        colorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder addAllColors(
        java.lang.Iterable<? extends c22dlink.ColorInfo> values) {
      if (colorsBuilder_ == null) {
        ensureColorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, colors_);
        onChanged();
      } else {
        colorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder clearColors() {
      if (colorsBuilder_ == null) {
        colors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        colorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public Builder removeColors(int index) {
      if (colorsBuilder_ == null) {
        ensureColorsIsMutable();
        colors_.remove(index);
        onChanged();
      } else {
        colorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public c22dlink.ColorInfo.Builder getColorsBuilder(
        int index) {
      return getColorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public c22dlink.ColorInfoOrBuilder getColorsOrBuilder(
        int index) {
      if (colorsBuilder_ == null) {
        return colors_.get(index);  } else {
        return colorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public java.util.List<? extends c22dlink.ColorInfoOrBuilder> 
         getColorsOrBuilderList() {
      if (colorsBuilder_ != null) {
        return colorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(colors_);
      }
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public c22dlink.ColorInfo.Builder addColorsBuilder() {
      return getColorsFieldBuilder().addBuilder(
          c22dlink.ColorInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public c22dlink.ColorInfo.Builder addColorsBuilder(
        int index) {
      return getColorsFieldBuilder().addBuilder(
          index, c22dlink.ColorInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .c22dlink.ColorInfo colors = 1;</code>
     */
    public java.util.List<c22dlink.ColorInfo.Builder> 
         getColorsBuilderList() {
      return getColorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        c22dlink.ColorInfo, c22dlink.ColorInfo.Builder, c22dlink.ColorInfoOrBuilder> 
        getColorsFieldBuilder() {
      if (colorsBuilder_ == null) {
        colorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            c22dlink.ColorInfo, c22dlink.ColorInfo.Builder, c22dlink.ColorInfoOrBuilder>(
                colors_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        colors_ = null;
      }
      return colorsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:c22dlink.ColorsInfo)
  }

  static {
    defaultInstance = new ColorsInfo(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:c22dlink.ColorsInfo)
}

