// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

package c22dlink;

/**
 * Protobuf type {@code c22dlink.FrameImage}
 */
public final class FrameImage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:c22dlink.FrameImage)
    FrameImageOrBuilder {
  // Use FrameImage.newBuilder() to construct.
  private FrameImage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private FrameImage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final FrameImage defaultInstance;
  public static FrameImage getDefaultInstance() {
    return defaultInstance;
  }

  public FrameImage getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private FrameImage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            sequence_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000004;
            width_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000008;
            height_ = input.readInt32();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000010;
            image_ = input.readBytes();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();
            c22dlink.FrameImage.Type value = c22dlink.FrameImage.Type.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(5, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              type_ = value;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return c22dlink.Frame.internal_static_c22dlink_FrameImage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return c22dlink.Frame.internal_static_c22dlink_FrameImage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            c22dlink.FrameImage.class, c22dlink.FrameImage.Builder.class);
  }

  public static com.google.protobuf.Parser<FrameImage> PARSER =
      new com.google.protobuf.AbstractParser<FrameImage>() {
    public FrameImage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FrameImage(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<FrameImage> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code c22dlink.FrameImage.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ORIGINAL = 1;</code>
     */
    ORIGINAL(0, 1),
    /**
     * <code>CLASSIFY = 2;</code>
     */
    CLASSIFY(1, 2),
    ;

    /**
     * <code>ORIGINAL = 1;</code>
     */
    public static final int ORIGINAL_VALUE = 1;
    /**
     * <code>CLASSIFY = 2;</code>
     */
    public static final int CLASSIFY_VALUE = 2;


    public final int getNumber() { return value; }

    public static Type valueOf(int value) {
      switch (value) {
        case 1: return ORIGINAL;
        case 2: return CLASSIFY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return c22dlink.FrameImage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:c22dlink.FrameImage.Type)
  }

  private int bitField0_;
  public static final int SEQUENCE_FIELD_NUMBER = 1;
  private int sequence_;
  /**
   * <code>required int32 sequence = 1;</code>
   */
  public boolean hasSequence() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 sequence = 1;</code>
   */
  public int getSequence() {
    return sequence_;
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private c22dlink.FrameImage.Type type_;
  /**
   * <code>required .c22dlink.FrameImage.Type type = 5 [default = ORIGINAL];</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .c22dlink.FrameImage.Type type = 5 [default = ORIGINAL];</code>
   */
  public c22dlink.FrameImage.Type getType() {
    return type_;
  }

  public static final int WIDTH_FIELD_NUMBER = 2;
  private int width_;
  /**
   * <code>required int32 width = 2;</code>
   */
  public boolean hasWidth() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 width = 2;</code>
   */
  public int getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 3;
  private int height_;
  /**
   * <code>required int32 height = 3;</code>
   */
  public boolean hasHeight() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int32 height = 3;</code>
   */
  public int getHeight() {
    return height_;
  }

  public static final int IMAGE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString image_;
  /**
   * <code>required bytes image = 4;</code>
   */
  public boolean hasImage() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required bytes image = 4;</code>
   */
  public com.google.protobuf.ByteString getImage() {
    return image_;
  }

  private void initFields() {
    sequence_ = 0;
    type_ = c22dlink.FrameImage.Type.ORIGINAL;
    width_ = 0;
    height_ = 0;
    image_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSequence()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasWidth()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasHeight()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasImage()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, sequence_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(2, width_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(3, height_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(4, image_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(5, type_.getNumber());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sequence_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, width_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, height_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, image_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, type_.getNumber());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static c22dlink.FrameImage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.FrameImage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.FrameImage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.FrameImage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.FrameImage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.FrameImage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static c22dlink.FrameImage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static c22dlink.FrameImage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static c22dlink.FrameImage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.FrameImage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(c22dlink.FrameImage prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code c22dlink.FrameImage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:c22dlink.FrameImage)
      c22dlink.FrameImageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return c22dlink.Frame.internal_static_c22dlink_FrameImage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return c22dlink.Frame.internal_static_c22dlink_FrameImage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              c22dlink.FrameImage.class, c22dlink.FrameImage.Builder.class);
    }

    // Construct using c22dlink.FrameImage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      sequence_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = c22dlink.FrameImage.Type.ORIGINAL;
      bitField0_ = (bitField0_ & ~0x00000002);
      width_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      height_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      image_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return c22dlink.Frame.internal_static_c22dlink_FrameImage_descriptor;
    }

    public c22dlink.FrameImage getDefaultInstanceForType() {
      return c22dlink.FrameImage.getDefaultInstance();
    }

    public c22dlink.FrameImage build() {
      c22dlink.FrameImage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public c22dlink.FrameImage buildPartial() {
      c22dlink.FrameImage result = new c22dlink.FrameImage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.sequence_ = sequence_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.width_ = width_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.height_ = height_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.image_ = image_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof c22dlink.FrameImage) {
        return mergeFrom((c22dlink.FrameImage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(c22dlink.FrameImage other) {
      if (other == c22dlink.FrameImage.getDefaultInstance()) return this;
      if (other.hasSequence()) {
        setSequence(other.getSequence());
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasWidth()) {
        setWidth(other.getWidth());
      }
      if (other.hasHeight()) {
        setHeight(other.getHeight());
      }
      if (other.hasImage()) {
        setImage(other.getImage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSequence()) {
        
        return false;
      }
      if (!hasType()) {
        
        return false;
      }
      if (!hasWidth()) {
        
        return false;
      }
      if (!hasHeight()) {
        
        return false;
      }
      if (!hasImage()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      c22dlink.FrameImage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (c22dlink.FrameImage) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int sequence_ ;
    /**
     * <code>required int32 sequence = 1;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sequence = 1;</code>
     */
    public int getSequence() {
      return sequence_;
    }
    /**
     * <code>required int32 sequence = 1;</code>
     */
    public Builder setSequence(int value) {
      bitField0_ |= 0x00000001;
      sequence_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 sequence = 1;</code>
     */
    public Builder clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sequence_ = 0;
      onChanged();
      return this;
    }

    private c22dlink.FrameImage.Type type_ = c22dlink.FrameImage.Type.ORIGINAL;
    /**
     * <code>required .c22dlink.FrameImage.Type type = 5 [default = ORIGINAL];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .c22dlink.FrameImage.Type type = 5 [default = ORIGINAL];</code>
     */
    public c22dlink.FrameImage.Type getType() {
      return type_;
    }
    /**
     * <code>required .c22dlink.FrameImage.Type type = 5 [default = ORIGINAL];</code>
     */
    public Builder setType(c22dlink.FrameImage.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .c22dlink.FrameImage.Type type = 5 [default = ORIGINAL];</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = c22dlink.FrameImage.Type.ORIGINAL;
      onChanged();
      return this;
    }

    private int width_ ;
    /**
     * <code>required int32 width = 2;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 width = 2;</code>
     */
    public int getWidth() {
      return width_;
    }
    /**
     * <code>required int32 width = 2;</code>
     */
    public Builder setWidth(int value) {
      bitField0_ |= 0x00000004;
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 width = 2;</code>
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000004);
      width_ = 0;
      onChanged();
      return this;
    }

    private int height_ ;
    /**
     * <code>required int32 height = 3;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 height = 3;</code>
     */
    public int getHeight() {
      return height_;
    }
    /**
     * <code>required int32 height = 3;</code>
     */
    public Builder setHeight(int value) {
      bitField0_ |= 0x00000008;
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 height = 3;</code>
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      height_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes image = 4;</code>
     */
    public boolean hasImage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes image = 4;</code>
     */
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }
    /**
     * <code>required bytes image = 4;</code>
     */
    public Builder setImage(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      image_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes image = 4;</code>
     */
    public Builder clearImage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      image_ = getDefaultInstance().getImage();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:c22dlink.FrameImage)
  }

  static {
    defaultInstance = new FrameImage(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:c22dlink.FrameImage)
}

