// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

package c22dlink;

public final class Frame {
  private Frame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_c22dlink_FrameImage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_c22dlink_FrameImage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013frame.proto\022\010c22dlink\"\243\001\n\nFrameImage\022\020" +
      "\n\010sequence\030\001 \002(\005\0221\n\004type\030\005 \002(\0162\031.c22dlin" +
      "k.FrameImage.Type:\010ORIGINAL\022\r\n\005width\030\002 \002" +
      "(\005\022\016\n\006height\030\003 \002(\005\022\r\n\005image\030\004 \002(\014\"\"\n\004Typ" +
      "e\022\014\n\010ORIGINAL\020\001\022\014\n\010CLASSIFY\020\002B\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_c22dlink_FrameImage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_c22dlink_FrameImage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_c22dlink_FrameImage_descriptor,
        new java.lang.String[] { "Sequence", "Type", "Width", "Height", "Image", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
