// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

public interface RequestColorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:c22dlink.RequestColors)
    com.google.protobuf.MessageOrBuilder {
}
