// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

/**
 * Protobuf type {@code c22dlink.RGB}
 */
public final class RGB extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:c22dlink.RGB)
    RGBOrBuilder {
  // Use RGB.newBuilder() to construct.
  private RGB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private RGB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final RGB defaultInstance;
  public static RGB getDefaultInstance() {
    return defaultInstance;
  }

  public RGB getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private RGB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            r_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            g_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            b_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return c22dlink.Colors.internal_static_c22dlink_RGB_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return c22dlink.Colors.internal_static_c22dlink_RGB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            c22dlink.RGB.class, c22dlink.RGB.Builder.class);
  }

  public static com.google.protobuf.Parser<RGB> PARSER =
      new com.google.protobuf.AbstractParser<RGB>() {
    public RGB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RGB(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<RGB> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int R_FIELD_NUMBER = 1;
  private int r_;
  /**
   * <code>required int32 r = 1;</code>
   */
  public boolean hasR() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 r = 1;</code>
   */
  public int getR() {
    return r_;
  }

  public static final int G_FIELD_NUMBER = 2;
  private int g_;
  /**
   * <code>required int32 g = 2;</code>
   */
  public boolean hasG() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 g = 2;</code>
   */
  public int getG() {
    return g_;
  }

  public static final int B_FIELD_NUMBER = 3;
  private int b_;
  /**
   * <code>required int32 b = 3;</code>
   */
  public boolean hasB() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 b = 3;</code>
   */
  public int getB() {
    return b_;
  }

  private void initFields() {
    r_ = 0;
    g_ = 0;
    b_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasR()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasG()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasB()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, r_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, g_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, b_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, r_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, g_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, b_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static c22dlink.RGB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.RGB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.RGB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.RGB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.RGB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.RGB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static c22dlink.RGB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static c22dlink.RGB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static c22dlink.RGB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.RGB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(c22dlink.RGB prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code c22dlink.RGB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:c22dlink.RGB)
      c22dlink.RGBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return c22dlink.Colors.internal_static_c22dlink_RGB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return c22dlink.Colors.internal_static_c22dlink_RGB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              c22dlink.RGB.class, c22dlink.RGB.Builder.class);
    }

    // Construct using c22dlink.RGB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      r_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      g_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      b_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return c22dlink.Colors.internal_static_c22dlink_RGB_descriptor;
    }

    public c22dlink.RGB getDefaultInstanceForType() {
      return c22dlink.RGB.getDefaultInstance();
    }

    public c22dlink.RGB build() {
      c22dlink.RGB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public c22dlink.RGB buildPartial() {
      c22dlink.RGB result = new c22dlink.RGB(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.r_ = r_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.g_ = g_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.b_ = b_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof c22dlink.RGB) {
        return mergeFrom((c22dlink.RGB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(c22dlink.RGB other) {
      if (other == c22dlink.RGB.getDefaultInstance()) return this;
      if (other.hasR()) {
        setR(other.getR());
      }
      if (other.hasG()) {
        setG(other.getG());
      }
      if (other.hasB()) {
        setB(other.getB());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasR()) {
        
        return false;
      }
      if (!hasG()) {
        
        return false;
      }
      if (!hasB()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      c22dlink.RGB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (c22dlink.RGB) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int r_ ;
    /**
     * <code>required int32 r = 1;</code>
     */
    public boolean hasR() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 r = 1;</code>
     */
    public int getR() {
      return r_;
    }
    /**
     * <code>required int32 r = 1;</code>
     */
    public Builder setR(int value) {
      bitField0_ |= 0x00000001;
      r_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 r = 1;</code>
     */
    public Builder clearR() {
      bitField0_ = (bitField0_ & ~0x00000001);
      r_ = 0;
      onChanged();
      return this;
    }

    private int g_ ;
    /**
     * <code>required int32 g = 2;</code>
     */
    public boolean hasG() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 g = 2;</code>
     */
    public int getG() {
      return g_;
    }
    /**
     * <code>required int32 g = 2;</code>
     */
    public Builder setG(int value) {
      bitField0_ |= 0x00000002;
      g_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 g = 2;</code>
     */
    public Builder clearG() {
      bitField0_ = (bitField0_ & ~0x00000002);
      g_ = 0;
      onChanged();
      return this;
    }

    private int b_ ;
    /**
     * <code>required int32 b = 3;</code>
     */
    public boolean hasB() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 b = 3;</code>
     */
    public int getB() {
      return b_;
    }
    /**
     * <code>required int32 b = 3;</code>
     */
    public Builder setB(int value) {
      bitField0_ |= 0x00000004;
      b_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 b = 3;</code>
     */
    public Builder clearB() {
      bitField0_ = (bitField0_ & ~0x00000004);
      b_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:c22dlink.RGB)
  }

  static {
    defaultInstance = new RGB(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:c22dlink.RGB)
}

