// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

public interface RGBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:c22dlink.RGB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 r = 1;</code>
   */
  boolean hasR();
  /**
   * <code>required int32 r = 1;</code>
   */
  int getR();

  /**
   * <code>required int32 g = 2;</code>
   */
  boolean hasG();
  /**
   * <code>required int32 g = 2;</code>
   */
  int getG();

  /**
   * <code>required int32 b = 3;</code>
   */
  boolean hasB();
  /**
   * <code>required int32 b = 3;</code>
   */
  int getB();
}
