// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

public interface SaveColorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:c22dlink.SaveColors)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string filename = 1;</code>
   */
  boolean hasFilename();
  /**
   * <code>required string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>required string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
