// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

/**
 * Protobuf type {@code c22dlink.YUV}
 */
public final class YUV extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:c22dlink.YUV)
    YUVOrBuilder {
  // Use YUV.newBuilder() to construct.
  private YUV(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private YUV(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final YUV defaultInstance;
  public static YUV getDefaultInstance() {
    return defaultInstance;
  }

  public YUV getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private YUV(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            y_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            u_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            v_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return c22dlink.Colors.internal_static_c22dlink_YUV_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return c22dlink.Colors.internal_static_c22dlink_YUV_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            c22dlink.YUV.class, c22dlink.YUV.Builder.class);
  }

  public static com.google.protobuf.Parser<YUV> PARSER =
      new com.google.protobuf.AbstractParser<YUV>() {
    public YUV parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new YUV(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<YUV> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int Y_FIELD_NUMBER = 1;
  private int y_;
  /**
   * <code>required int32 y = 1;</code>
   */
  public boolean hasY() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 y = 1;</code>
   */
  public int getY() {
    return y_;
  }

  public static final int U_FIELD_NUMBER = 2;
  private int u_;
  /**
   * <code>required int32 u = 2;</code>
   */
  public boolean hasU() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 u = 2;</code>
   */
  public int getU() {
    return u_;
  }

  public static final int V_FIELD_NUMBER = 3;
  private int v_;
  /**
   * <code>required int32 v = 3;</code>
   */
  public boolean hasV() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 v = 3;</code>
   */
  public int getV() {
    return v_;
  }

  private void initFields() {
    y_ = 0;
    u_ = 0;
    v_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasY()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasU()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasV()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, y_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, u_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, v_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, y_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, u_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, v_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static c22dlink.YUV parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.YUV parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.YUV parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static c22dlink.YUV parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static c22dlink.YUV parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.YUV parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static c22dlink.YUV parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static c22dlink.YUV parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static c22dlink.YUV parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static c22dlink.YUV parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(c22dlink.YUV prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code c22dlink.YUV}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:c22dlink.YUV)
      c22dlink.YUVOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return c22dlink.Colors.internal_static_c22dlink_YUV_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return c22dlink.Colors.internal_static_c22dlink_YUV_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              c22dlink.YUV.class, c22dlink.YUV.Builder.class);
    }

    // Construct using c22dlink.YUV.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      y_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      u_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      v_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return c22dlink.Colors.internal_static_c22dlink_YUV_descriptor;
    }

    public c22dlink.YUV getDefaultInstanceForType() {
      return c22dlink.YUV.getDefaultInstance();
    }

    public c22dlink.YUV build() {
      c22dlink.YUV result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public c22dlink.YUV buildPartial() {
      c22dlink.YUV result = new c22dlink.YUV(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.y_ = y_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.u_ = u_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.v_ = v_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof c22dlink.YUV) {
        return mergeFrom((c22dlink.YUV)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(c22dlink.YUV other) {
      if (other == c22dlink.YUV.getDefaultInstance()) return this;
      if (other.hasY()) {
        setY(other.getY());
      }
      if (other.hasU()) {
        setU(other.getU());
      }
      if (other.hasV()) {
        setV(other.getV());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasY()) {
        
        return false;
      }
      if (!hasU()) {
        
        return false;
      }
      if (!hasV()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      c22dlink.YUV parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (c22dlink.YUV) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int y_ ;
    /**
     * <code>required int32 y = 1;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 y = 1;</code>
     */
    public int getY() {
      return y_;
    }
    /**
     * <code>required int32 y = 1;</code>
     */
    public Builder setY(int value) {
      bitField0_ |= 0x00000001;
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 y = 1;</code>
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000001);
      y_ = 0;
      onChanged();
      return this;
    }

    private int u_ ;
    /**
     * <code>required int32 u = 2;</code>
     */
    public boolean hasU() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 u = 2;</code>
     */
    public int getU() {
      return u_;
    }
    /**
     * <code>required int32 u = 2;</code>
     */
    public Builder setU(int value) {
      bitField0_ |= 0x00000002;
      u_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 u = 2;</code>
     */
    public Builder clearU() {
      bitField0_ = (bitField0_ & ~0x00000002);
      u_ = 0;
      onChanged();
      return this;
    }

    private int v_ ;
    /**
     * <code>required int32 v = 3;</code>
     */
    public boolean hasV() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 v = 3;</code>
     */
    public int getV() {
      return v_;
    }
    /**
     * <code>required int32 v = 3;</code>
     */
    public Builder setV(int value) {
      bitField0_ |= 0x00000004;
      v_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 v = 3;</code>
     */
    public Builder clearV() {
      bitField0_ = (bitField0_ & ~0x00000004);
      v_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:c22dlink.YUV)
  }

  static {
    defaultInstance = new YUV(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:c22dlink.YUV)
}

