// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: colors.proto

package c22dlink;

public interface YUVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:c22dlink.YUV)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 y = 1;</code>
   */
  boolean hasY();
  /**
   * <code>required int32 y = 1;</code>
   */
  int getY();

  /**
   * <code>required int32 u = 2;</code>
   */
  boolean hasU();
  /**
   * <code>required int32 u = 2;</code>
   */
  int getU();

  /**
   * <code>required int32 v = 3;</code>
   */
  boolean hasV();
  /**
   * <code>required int32 v = 3;</code>
   */
  int getV();
}
